phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=ASGGitHubAccount -Dsonar.organization=kadenf103 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN

