version: 0.1
phases:
	build:
		commands:
			- mvn verify sonar:sonar -Dsonar.ProjectKey=ASGGitHubAccount  -Dsonar.organization=ASGGitHubAccount -Dsonar.host.url.https://sonarcloud.io -Dsonar.login=c1fcf4d345606ed5dddc20e246b52cbc5a89e7af